apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: myapp
      version: green

  template:
    metadata:
      labels:
        app: myapp
        version: green

    spec:
      containers:
        - name: green-container
          image: nginx
          ports:
            - containerPort: 80
          command: ["/bin/sh"]
          args:
            - -c
            - |
              echo "<h1 style='color:green'>GREEN VERSION</h1>" > /usr/share/nginx/html/index.html
              nginx -g 'daemon off;';