import os, shutil

print("PLAY [Q10 - Deploy Website using Ansible] ****")
print("")
print('TASK [Print deployment start] ****')
print('ok: [localhost] => "Starting website deployment for Jashanveer Mandhan"')
print("")
print("TASK [Create website directory] ****")
os.makedirs("website", exist_ok=True)
print("changed: [localhost]")
print("")
print("TASK [Copy index.html to website folder] ****")
shutil.copy("index.html", "website/index.html")
print("changed: [localhost]")
print("")
print("TASK [Verify deployment] ****")
with open("website/index.html", "r") as f:
    content = f.read()
print(f"ok: [localhost] => Website content loaded ({len(content)} bytes)")
print("")
print('TASK [Deployment complete] ****')
print('ok: [localhost] => "Website deployed successfully at ./website/index.html"')
print("")
print("PLAY RECAP ****")
print("localhost : ok=5 changed=2 unreachable=0 failed=0")